<?php

//test comment please ignore

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CpuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cpu1=new \App\Models\Cpu();
        $cpu1->price=218.49;
        $cpu1->brand='amd';
        $cpu1->model='Ryzen 5 1600 3.2GHz 6-Core Processor';
        $cpu1->data_width='64-bit';
        $cpu1->socket_type='am4';
        $cpu1->operating_frequency='3.2ghz';
        $cpu1->max_turbo_frequency='3.6ghz';
        $cpu1->number_of_cores=6;
        $cpu1->l1_cache='6x64kb instruction, 6x32kb data';
        $cpu1->l2_cache='6x512kb';
        $cpu1->l3_cache='2x8mb';
        $cpu1->wattage=65;
        $cpu1->hyperthreading_support='yes';
        $cpu1->max_supported_memory='0';
        $cpu1->intergrated_graphics='no';
        $cpu1->save();
        
        $cpu2=new \App\Models\Cpu();
        $cpu2->price=188.59;
        $cpu2->brand='intel';
        $cpu2->model='Core i5-7500 3.4GHz Quad-Core Processor';
        $cpu2->data_width='64-bit';
        $cpu2->socket_type='lga1151';
        $cpu2->operating_frequency='3.4ghz';
        $cpu2->max_turbo_frequency='3.8ghz';
        $cpu2->number_of_cores=4;
        $cpu2->l1_cache='4x32kb instruction, 4x32kb data';
        $cpu2->l2_cache='4x256kb';
        $cpu2->l3_cache='1x6mb';
        $cpu2->wattage=65;
        $cpu2->hyperthreading_support='no';
        $cpu2->max_supported_memory=64;
        $cpu2->intergrated_graphics='intel hd graphics 630';
        $cpu2->save();
        
        $cpu3=new \App\Models\Cpu();
        $cpu3->price=228.79;
        $cpu3->brand='intel';
        $cpu3->model='Core i5-7600K 3.8GHz Quad-Core Processor';
        $cpu3->data_width='64-bit';
        $cpu3->socket_type='lga1151';
        $cpu3->operating_frequency='3.8ghz';
        $cpu3->max_turbo_frequency='4.2ghz';
        $cpu3->number_of_cores=4;
        $cpu3->l1_cache='4x32kb instruction, 4x32kb data';
        $cpu3->l2_cache='4x256kb';
        $cpu3->l3_cache='1x6mb';
        $cpu3->wattage=91;
        $cpu3->hyperthreading_support='no';
        $cpu3->max_supported_memory=64;
        $cpu3->intergrated_graphics='intel hd graphics 630';
        $cpu3->save();
        
        $cpu4=new \App\Models\Cpu();
        $cpu4->price=328.47;
        $cpu4->brand='intel';
        $cpu4->model='Core i7-7700K 4.2GHz Quad-Core Processor';
        $cpu4->data_width='64-bit';
        $cpu4->socket_type='lga1151';
        $cpu4->operating_frequency='4.2ghz';
        $cpu4->max_turbo_frequency='4.5ghz';
        $cpu4->number_of_cores=4;
        $cpu4->l1_cache='4x32kb instruction, 4x32kb data';
        $cpu4->l2_cache='4x256kb';
        $cpu4->l3_cache='1x8mb';
        $cpu4->wattage=91;
        $cpu4->hyperthreading_support='yes';
        $cpu4->max_supported_memory=64;
        $cpu4->intergrated_graphics='intel hd graphics 630';
        $cpu4->save();
        
        $cpu5=new \App\Models\Cpu();
        $cpu5->price=165.88;
        $cpu5->brand='amd';
        $cpu5->model='Ryzen 5 1400 3.2GHz Quad-Core Processor';
        $cpu5->data_width='64-bit';
        $cpu5->socket_type='am4';
        $cpu5->operating_frequency='3.2ghz';
        $cpu5->max_turbo_frequency='3.4ghz';
        $cpu5->number_of_cores=4;
        $cpu5->l1_cache='4 x 64KB Instruction, 4 x 32KB Data';
        $cpu5->l2_cache='4 x 512KB ';
        $cpu5->l3_cache='1 x 8MB ';
        $cpu5->wattage=65;
        $cpu5->hyperthreading_support='yes';
        $cpu5->max_supported_memory='0';
        $cpu5->intergrated_graphics='no';
        $cpu5->save();
        
        $cpu6=new \App\Models\Cpu();
        $cpu6->price=219.99;
        $cpu6->brand='intel';
        $cpu6->model='Core i5-6600K 3.5GHz Quad-Core Processor';
        $cpu6->data_width='64-bit';
        $cpu6->socket_type='lga1151';
        $cpu6->operating_frequency='3.5ghz';
        $cpu6->max_turbo_frequency='3.9ghz';
        $cpu6->number_of_cores=4;
        $cpu6->l1_cache='4 x 32KB Instruction, 4 x 32KB Data';
        $cpu6->l2_cache='4 x 256KB ';
        $cpu6->l3_cache='1 x 6MB ';
        $cpu6->wattage=91;
        $cpu6->hyperthreading_support='no';
        $cpu6->max_supported_memory='0';
        $cpu6->intergrated_graphics='Intel HD Graphics 530';
        $cpu6->save();
        
        $cpu7=new \App\Models\Cpu();
        $cpu7->price=305.06;
        $cpu7->brand='intel';
        $cpu7->model='Core i7-6700K 4.0GHz Quad-Core Processor';
        $cpu7->data_width='64-bit';
        $cpu7->socket_type='lga1151';
        $cpu7->operating_frequency='4.0ghz';
        $cpu7->max_turbo_frequency='4.2ghz';
        $cpu7->number_of_cores='4';
        $cpu7->l1_cache='4 x 32KB Instruction, 4 x 32KB Data';
        $cpu7->l2_cache='4 x 256KB ';
        $cpu7->l3_cache='1 x 8MB ';
        $cpu7->wattage=91;
        $cpu7->hyperthreading_support='yes';
        $cpu7->max_supported_memory=64;
        $cpu7->intergrated_graphics='Intel HD Graphics 530';
        $cpu7->save();
        
        $cpu8=new \App\Models\Cpu();
        $cpu8->price=57.88;
        $cpu8->brand='intel';
        $cpu8->model='Pentium G4560 3.5GHz Dual-Core Processor';
        $cpu8->data_width='64-bit';
        $cpu8->socket_type='lga1151';
        $cpu8->operating_frequency='3.5ghz';
        $cpu8->max_turbo_frequency='none';
        $cpu8->number_of_cores=2;
        $cpu8->l1_cache='2 x 32KB Instruction, 2 x 32KB Data';
        $cpu8->l2_cache='2 x 256KB ';
        $cpu8->l3_cache='1 x 3MB ';
        $cpu8->wattage=54;
        $cpu8->hyperthreading_support='yes';
        $cpu8->max_supported_memory=64;
        $cpu8->intergrated_graphics='Intel HD Graphics 610 ';
        $cpu8->save();
        
        $cpu9=new \App\Models\Cpu();
        $cpu9->price=188.98;
        $cpu9->brand='amd';
        $cpu9->model='Ryzen 5 1500X 3.5GHz Quad-Core Processor';
        $cpu9->data_width='64-bit';
        $cpu9->socket_type='am4';
        $cpu9->operating_frequency=' 3.5GHz ';
        $cpu9->max_turbo_frequency=' 3.7GHz ';
        $cpu9->number_of_cores=4;
        $cpu9->l1_cache='4 x 64KB Instruction,4 x 32KB Data';
        $cpu9->l2_cache=' 4 x 512KB ';
        $cpu9->l3_cache=' 2 x 8MB ';
        $cpu9->wattage=65;
        $cpu9->hyperthreading_support='yes';
        $cpu9->max_supported_memory='0';
        $cpu9->intergrated_graphics='no';
        $cpu9->save();
        
        $cpu10=new \App\Models\Cpu();
        $cpu10->price=247.88;
        $cpu10->brand='amd';
        $cpu10->model='Ryzen 5 1600X 3.6GHz 6-Core Processor';
        $cpu10->data_width='64-bit';
        $cpu10->socket_type='am4';
        $cpu10->operating_frequency='3.6ghz';
        $cpu10->max_turbo_frequency='4.0ghz';
        $cpu10->number_of_cores='6';
        $cpu10->l1_cache='6 x 64KB Instruction, 6 x 32KB Data';
        $cpu10->l2_cache=' 6 x 512KB ';
        $cpu10->l3_cache=' 2 x 8MB ';
        $cpu10->wattage=95;
        $cpu10->hyperthreading_support='yes';
        $cpu10->max_supported_memory='0';
        $cpu10->intergrated_graphics='no';
        $cpu10->save();
        
        $cpu11=new \App\Models\Cpu();
        $cpu11->price=310.90;
        $cpu11->brand='amd';
        $cpu11->model='Ryzen 7 1700 3.0GHz 8-Core Processor';
        $cpu11->data_width='64-bit';
        $cpu11->socket_type='am4';
        $cpu11->operating_frequency='3.0ghz';
        $cpu11->max_turbo_frequency='3.7ghz';
        $cpu11->number_of_cores=8;
        $cpu11->l1_cache='8 x 64KB Instruction, 8 x 32KB Data';
        $cpu11->l2_cache=' 8 x 512KB ';
        $cpu11->l3_cache=' 2 x 8MB ';
        $cpu11->wattage=65;
        $cpu11->hyperthreading_support='yes';
        $cpu11->max_supported_memory='0';
        $cpu11->intergrated_graphics='no';
        $cpu11->save();
        
        $cpu12=new \App\Models\Cpu();
        $cpu12->price=108.75;
        $cpu12->brand='intel';
        $cpu12->model='Core i3-6100 3.7GHz Dual-Core Processor';
        $cpu12->data_width='64-bit';
        $cpu12->socket_type='lga1151';
        $cpu12->operating_frequency='3.7ghz';
        $cpu12->max_turbo_frequency='none';
        $cpu12->number_of_cores=2;
        $cpu12->l1_cache='2 x 32KB Instruction, 2 x 32KB Data';
        $cpu12->l2_cache=' 2 x 256KB ';
        $cpu12->l3_cache=' 1 x 3MB ';
        $cpu12->wattage=51;
        $cpu12->hyperthreading_support='yes';
        $cpu12->max_supported_memory=64;
        $cpu12->intergrated_graphics='intel HD Graphics 530';
        $cpu12->save();
        
        $cpu13=new \App\Models\Cpu();
        $cpu13->price=120.89;
        $cpu13->brand='amd';
        $cpu13->model='FX-8350 4.0GHz 8-Core Processor';
        $cpu13->data_width='64-bit';
        $cpu13->socket_type=' AM3+ ';
        $cpu13->operating_frequency='4.0ghz';
        $cpu13->max_turbo_frequency='none';
        $cpu13->number_of_cores=8;
        $cpu13->l1_cache='4 x 64KB Instruction, 8 x 16KB Data';
        $cpu13->l2_cache=' 4 x 2MB ';
        $cpu13->l3_cache=' 1 x 8MB ';
        $cpu13->wattage=125;
        $cpu13->hyperthreading_support='no';
        $cpu13->max_supported_memory='0';
        $cpu13->intergrated_graphics='no';
        $cpu13->save();
        
        $cpu14=new \App\Models\Cpu();
        $cpu14->price=342.84;
        $cpu14->brand='amd';
        $cpu14->model='Ryzen 7 1700X 3.4GHz 8-Core Processor';
        $cpu14->data_width='64-bit';
        $cpu14->socket_type='AM4';
        $cpu14->operating_frequency='3.4ghz';
        $cpu14->max_turbo_frequency='3.8ghz';
        $cpu14->number_of_cores=8;
        $cpu14->l1_cache='8 x 64KB Instruction, 8 x 32KB Data';
        $cpu14->l2_cache=' 8 x 512KB ';
        $cpu14->l3_cache=' 2 x 8MB ';
        $cpu14->wattage=95;
        $cpu14->hyperthreading_support='yes';
        $cpu14->max_supported_memory='0';
        $cpu14->intergrated_graphics='no';
        $cpu14->save();
        
        $cpu15=new \App\Models\Cpu();
        $cpu15->price=464.79;
        $cpu15->brand='amd';
        $cpu15->model='Ryzen 7 1800X 3.6GHz 8-Core Processor';
        $cpu15->data_width='64-bit';
        $cpu15->socket_type='am4';
        $cpu15->operating_frequency='3.6ghz';
        $cpu15->max_turbo_frequency='4.0ghz';
        $cpu15->number_of_cores=8;
        $cpu15->l1_cache='8 x 64KB Instruction, 8 x 32KB Data';
        $cpu15->l2_cache='8 x 512KB';
        $cpu15->l3_cache='2 x 8MB';
        $cpu15->wattage=95;
        $cpu15->hyperthreading_support='yes';
        $cpu15->max_supported_memory='0';
        $cpu15->intergrated_graphics='no';
        $cpu15->save();
        
        $cpu16=new \App\Models\Cpu();
        $cpu16->price=187.89;
        $cpu16->brand='intel';
        $cpu16->model='Core i5-6500 3.2GHz Quad-Core Processor';
        $cpu16->data_width='64-bit';
        $cpu16->socket_type='lga1151';
        $cpu16->operating_frequency='3.2ghz';
        $cpu16->max_turbo_frequency='3.6ghz';
        $cpu16->number_of_cores=4;
        $cpu16->l1_cache='4 x 32KB Instruction, 4 x 32KB Data';
        $cpu16->l2_cache='4 x 256KB';
        $cpu16->l3_cache='1 x 6MB';
        $cpu16->wattage=65;
        $cpu16->hyperthreading_support='no';
        $cpu16->max_supported_memory=64;
        $cpu16->intergrated_graphics='intel HD graphics 530';
        $cpu16->save();
        
        $cpu17=new \App\Models\Cpu();
        $cpu17->price=77.59;
        $cpu17->brand='amd';
        $cpu17->model='FX-6300 3.5GHz 6-Core Processor';
        $cpu17->data_width='64-bit';
        $cpu17->socket_type='am3';
        $cpu17->operating_frequency='3.5ghz';
        $cpu17->max_turbo_frequency='none';
        $cpu17->number_of_cores=6;
        $cpu17->l1_cache='3 x 64KB Instruction, 6 x 16KB Data';
        $cpu17->l2_cache=' 3 x 2MB ';
        $cpu17->l3_cache=' 1 x 8MB ';
        $cpu17->wattage=95;
        $cpu17->hyperthreading_support='no';
        $cpu17->max_supported_memory='0';
        $cpu17->intergrated_graphics='no';
        $cpu17->save();
        
        $cpu18=new \App\Models\Cpu();
        $cpu18->price=110.88;
        $cpu18->brand='intel';
        $cpu18->model='Core i3-7100 3.9GHz Dual-Core Processor';
        $cpu18->data_width='64-bit';
        $cpu18->socket_type='lga1151';
        $cpu18->operating_frequency='3.9ghz';
        $cpu18->max_turbo_frequency='none';
        $cpu18->number_of_cores=2;
        $cpu18->l1_cache='2 x 32KB Instruction,2 x 32KB Data' ;
        $cpu18->l2_cache=' 2 x 256KB ';
        $cpu18->l3_cache=' 1 x 3MB ';
        $cpu18->wattage=51;
        $cpu18->hyperthreading_support='yes';
        $cpu18->max_supported_memory=64;
        $cpu18->intergrated_graphics='intel HD graphics 630';
        $cpu18->save();
        
        $cpu19=new \App\Models\Cpu();
        $cpu19->price=176.44;
        $cpu19->brand='intel';
        $cpu19->model='Core i5-7400 3.0GHz Quad-Core Processor';
        $cpu19->data_width='64-bit';
        $cpu19->socket_type='lga1151';
        $cpu19->operating_frequency='3.0ghz';
        $cpu19->max_turbo_frequency='3.5ghz';
        $cpu19->number_of_cores=4;
        $cpu19->l1_cache='4 x 32KB Instruction, 4 x 32KB Data';
        $cpu19->l2_cache=' 4 x 256KB ';
        $cpu19->l3_cache=' 1 x 6MB ';
        $cpu19->wattage=65;
        $cpu19->hyperthreading_support='yes';
        $cpu19->max_supported_memory=64;
        $cpu19->intergrated_graphics='intel HD graphics 630';
        $cpu19->save();
        
        $cpu20=new \App\Models\Cpu();
        $cpu20->price=294.98;
        $cpu20->brand='intel';
        $cpu20->model='Core i7-7700 3.6GHz Quad-Core Processor';
        $cpu20->data_width='64-bit';
        $cpu20->socket_type='lga1151';
        $cpu20->operating_frequency='3.6ghz';
        $cpu20->max_turbo_frequency='4.2ghz';
        $cpu20->number_of_cores=4;
        $cpu20->l1_cache='4 x 32KB Instruction,4 x 32KB Data';
        $cpu20->l2_cache=' 4 x 256KB ';
        $cpu20->l3_cache=' 1 x 8MB ';
        $cpu20->wattage=65;
        $cpu20->hyperthreading_support='yes';
        $cpu20->max_supported_memory=64;
        $cpu20->intergrated_graphics='intel HD graphics 630';
        $cpu20->save();
    }
}
